### ISSUE TITLE
Hitting API Rate limit

### ISSUE THREAD

**Issue by warwick-mitchell1** [uptime-com/terraform-provider-uptime#1]
Have to run terraform multiple times as we always hit the API rate limit. Could the provider factor this in?
Tried to slow down Terraform with `-parallelism=1` and still hitting it.

 PATCH https://uptime.com/api/v1/checks/xxxxx/ failed: Code=API_RATE_LIMIT Message=Sorry, your recent action hit the account API fair use limit and has been throttled. You may retry in 34 seconds

**Comment by swathikrishnaguru** [comment]
> please make the provider slow down operation Can be done like that: [Mastercard/terraform-provider-restapi#71](https://github.com/Mastercard/terraform-provider-restapi/pull/71)

How this can be used in terraform? Any examples?

**Comment by bazzisoft** [comment]
We now have added functionality where API rate limits specifically for managing checks can be increased on a per-account basis, via a request to support@uptime.com. (Please note this is a paid feature). This allows a large number of checks to be provisioned via Terraform quickly, without requiring artificial delays between API calls.
