### ISSUE TITLE
Support specifying encryption in TCP checks

### ISSUE THREAD

**Issue by mikroskeem** [uptime-com/terraform-provider-uptime#101]
Currently TCP check resource does not support specifying encryption in the definition, thus all created checks default to SSL/TLS being enabled.

One would expect that creating TCP check does not necessarily mean SSL/TLS.

Preliminary research revealed that:
1) From API if SSL/TLS is enabled, `msp_encryption` is `SSL_TLS` and if it's off, then it's empty string.
2) uptime-client-go does not have this field specified

I would like to work on implementing this, however how should `encryption` field be defined in the resource? Are there plans to support some other value there, or would simple boolean be sufficient?

**Comment by mikroskeem** [comment]
Seems like other resources which expose `encryption` field, take it in as a string

**Comment by gigovich** [comment]
Hello, @mikroskeem
Thank you for your work on this project. I already merged your PR for an uptime client. Also, I checked #102 it looks ok, only two notes:
1. Documentation is generated automatically by the `go generate ./...` command, so please don't update it manually; just move it to the `Description` property of the `encryption` field. (Yes, we use a string field, and it can be extended in the future by new values.) and then run `go generate ./...`.
2. Please add an acceptance test with two cases, with/without the `encryption` field.

Please ping me if you need any help with this PR.
