### ISSUE TITLE
Bug when trying to create a tag

### ISSUE THREAD

**Issue by Courtcircuits** [uptime-com/terraform-provider-uptime#104]
When trying to create an `uptime_check_http` with a `tag` field I get the following error : 
```
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to uptime_check_http.http, provider "provider[\"registry.terraform.io/uptime-com/uptime\"]" produced an unexpected new value: .tags: planned set element
│ cty.StringVal("123392") does not correlate with any element in actual.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```
Here is my code. Note that I create the tag in the same run as the check.
```hcl
resource "uptime_check_http" "http" {
  name           = "Example HTTP Check"
  address        = "<>"
  contact_groups = ["Default"]
  tags = [uptime_tag.tag.id]

  interval  = 5
}

resource "uptime_tag" "tag" {
  tag = "crf"
  color_hex = "#abc0ff"
}

resource "uptime_statuspage" "statuspage" {
  name = "<>"
  company_website_url = "<>"
  allow_pdf_report = true
}
```
The tag and http check are created correctly but since I get a terraform error I can't use this provider for production work for now

**Comment by nabadger** [comment]
Wouldn't it be:

```
resource "uptime_check_http" "http" {
  name           = "Example HTTP Check"
  address        = "<>"
  contact_groups = ["Default"]
  tags = [uptime_tag.tag.tag]

  interval  = 5
}
```

Tags is working for us, but we don't provision it in the same code.

So we actually end up doing something like:

```
resource "uptime_check_http" "http" {
  name           = "Example HTTP Check"
  address        = "<>"
  contact_groups = ["Default"]
  tags = ["crf"]

  interval  = 5
}

**Comment by gigovich** [comment]
Thank you @Courtcircuits,
I'll check it and try to reproduce it.

**Comment by gigovich** [comment]
@Courtcircuits, sorry for the delay; @nabadger was right about tags field notation. As check resources (actually all others, too) work with tag names themselves, not their IDs, the issue in the HTTP resource check definition is using tag names.
So the only change you need to try is:
```
 tags = [uptime_tag.tag.tag]
```
I closed this issue until you have any new incident with that case.
