### ISSUE TITLE
Add support for the API check type

### ISSUE THREAD

**Issue by gk-mevers** [uptime-com/terraform-provider-uptime#11]
Currently, the API check type is not supported by the Terraform provider. It is, however, supported by the API. Can you add support for the API check type to the provider?

**Comment by bazzisoft** [comment]
Hey @gk-mevers , definitely seems to be a worthwhile addition. We'll add this to our roadmap for the provider.

**Comment by mikluko** [comment]
@gk-mevers Please check out latest provider release: https://registry.terraform.io/providers/uptime-com/uptime/latest/docs/resources/check_api

**Comment by gk-mevers** [comment]
Thank you very much. I will check it out.
