### ISSUE TITLE
Password field is shown clear text on plan and always triggers change

### ISSUE THREAD

**Issue by warwick-mitchell1** [uptime-com/terraform-provider-uptime#2]
For `uptime_check_http` resource (and maybe others) the password field isn't marked as sensitive so is always show clear text in the plan. 

Also it triggers every plan as if it's been changed but it hasn't. I've used a lifecycle ignore_changes rule for now to get around this.

**Comment by mikluko** [comment]
It was partially addressed by #14. Password field is now treated as sensitive.

**Comment by mikluko** [comment]
The part where password makes resource constantly outdated will be addressed separately.

**Comment by mikluko** [comment]
Password triggering resource update on every run is fixed with #16
