### ISSUE TITLE
probe servers ip range data source

### ISSUE THREAD

**Issue by evgenimi** [uptime-com/terraform-provider-uptime#23]
hi uptime team,

could be great if you expose all the probe server public IPs by API.
and then adding a Terraform data source to query it.

a good example can be found in Terraform cloud enterprise provider:
here: https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/ip_ranges
https://developer.hashicorp.com/terraform/cloud-docs/api-docs/ip-ranges

**Comment by mikluko** [comment]
Hi @evgenimi,

Thanks for your feature request!

Information you require is available at the following API endpoint: [/api/v1/probe-servers/](https://uptime.com/api/v1/docs/#/probe-servers)

Data sources is a planned feature but I don't have any timeline for it at hands.

**Comment by mikluko** [comment]
@evgenimi [v2.0.0-beta.2](https://registry.terraform.io/providers/uptime-com/uptime/2.0.0-beta.2) has been released. The release includes [uptime_locations data source](https://registry.terraform.io/providers/uptime-com/uptime/latest/docs/data-sources/locations). Please let me know how/if that fits your use case.
