### ISSUE TITLE
Accepted values for encryption in http_checks

### ISSUE THREAD

**Issue by cirojascr** [uptime-com/terraform-provider-uptime#27]
Using this module https://registry.terraform.io/providers/uptime-com/uptime/latest/docs/resources/check_http#encryption for the attribute `encryption` there is no way to know what the accepted values are. I tried using 'Off', 'False', 'false, etc, I see in Go code the accepted value type is string, but nothing more.

**Comment by bazzisoft** [comment]
Hi @cirojascr, you're right we definitely need to do a better job of documenting these parameters... This and other similar fields are enum fields that match our REST API which Terraform uses directly, so you can get the values from our REST API docs:

https://uptime.com/api/v1/docs/#/checks/post_service_create_http

In this case for the "encryption" field, the valid values are <blank> to disable certificate verification or `SSL_TLS` to enable verification of SSL certificates. (Note that whether SSL/TLS is actually used depends on the URL scheme (https://) for HTTP checks, after processing redirects.
