### ISSUE TITLE
Feature Request - Add options missing in the provider

### ISSUE THREAD

**Issue by vikas027** [uptime-com/terraform-provider-uptime#31]
I have gone through the [documentation](https://registry.terraform.io/providers/uptime-com/uptime/latest/docs/resources/check_http) but could not find a few options that are available in the UI.

![2023-10-10_16-10-37](https://github.com/uptime-com/terraform-provider-uptime/assets/6998650/4abe35b1-0e9a-46a7-8b62-7a17466dd3da)
![2023-10-10_16-11-09](https://github.com/uptime-com/terraform-provider-uptime/assets/6998650/07a9ba30-7e68-4f39-a543-f01af8287294)

**Comment by mikluko** [comment]
@vikas027 

We have added most of HTTP check GUI options to the provider. See https://registry.terraform.io/providers/uptime-com/uptime/2.1.0-rc.2/docs/resources/check_http

One significant exception is escalations. Provider does not support escalations at the moment. Implementing these is not specific to HTTP check and I belive should be tracked in a separate issue.
