### ISSUE TITLE
Add maintenance windows to uptime_check_http

### ISSUE THREAD

**Issue by CameronFurbushSM** [uptime-com/terraform-provider-uptime#40]
Hello! We're using the uptime_check_http resources for managing our HTTP checks. One feature we're looking to start using is the maintenance window setting this would be a great addition.

<img width="988" alt="image" src="https://github.com/uptime-com/terraform-provider-uptime/assets/140416756/0a890d17-0f2d-4dfc-98f7-1d299868e1ba">

**Comment by fcbry** [comment]
+1 on this, there's a couple of not yet released websites we want to monitor but put into maintenance mode for the next couple of months (so we don't get notifications firing).

**Comment by nabadger** [comment]
Another +1 on this. In some cases I think we're seeing that even if we set the maintenance period manually, subsequent tf applies seem to unset this. We'll need to find a way to workaround this in the meantime.

**Comment by gigovich** [comment]
We plan to release this feature next week.

**Comment by fcbry** [comment]
Ah wonderful, that will make my job a lot easier, thanks for the updated!

Bryan

PGP Key Info : 5ae2ffd8adbc9461<https://keyserver.ubuntu.com/pks/lookup?search=5ae2ffd8adbc9461+&fingerprint=on&op=index>
________________________________

**Comment by gigovich** [comment]
Hey there,
A fresh version has been released with this feature (v2.9.0).
[Here you can find](https://github.com/uptime-com/terraform-provider-uptime/tree/main/internal/provider/testdata/resource_check_maintenance) an example of how to set maintenance windows for checks.
