### ISSUE TITLE
Setting Status_Code value to empty string to allow following redirects - produces error 

### ISSUE THREAD

**Issue by avivek** [uptime-com/terraform-provider-uptime#74]
In an http_check when we leave the status_code field unspecified a default value of 200 gets applied and this leads to uptime not following redirects. In the UI the default value of this field is empty.

To allow for uptime to follow redirects we set the status_code value in terraform to empty string "" . This lead to the below error:

 "provider[\"registry.terraform.io/uptime-com/uptime\"]" produced an
 unexpected new value: .status_code: was cty.StringVal(""), but now
 cty.StringVal("200")

How do we set the status code value to empty using the uptime terraform provider??

**Comment by avivek** [comment]
I see that a PR for this has been merged. Is there a release being planned??

**Comment by gigovich** [comment]
@avivek, we plan to release it on Monday (13.05.2024).

**Comment by gigovich** [comment]
@avivek release, which fixes this issue, was published in the TF registry (version 2.4.3).
