### ISSUE TITLE
Adding components / groups to status page

### ISSUE THREAD

**Issue by marevers** [uptime-com/terraform-provider-uptime#96]
Hello,

For the `uptime_statuspage` resource, the documentation shows a lot of options but I am unable to find an option to actually add groups and components to the status page. Is this described somewhere? Or is not supported by the resource, as in, you can only do the initial setup of the status page with Terraform and then the selection of groups / components manually?

Best regards,
Martijn Evers

**Comment by gigovich** [comment]
Hello @marevers 
I'm sorry for not getting back to you sooner. We need to implement status page components and add them to our roadmap for next month.

**Comment by marevers** [comment]
Thank you!

**Comment by gigovich** [comment]
@marevers a new release [2.10.0](https://registry.terraform.io/providers/uptime-com/uptime/2.10.0) contains resources to fully setup status page.
