### ISSUE TITLE
Support sensitivity in ICMP check

### ISSUE THREAD

**Issue by hatamiarash7** [uptime-com/terraform-provider-uptime#97]
Hello

Currently, we can't set `sensitivity` value for `uptime_check_icmp` checks. For example, we can define that for [HTTP checks](https://github.com/uptime-com/terraform-provider-uptime/blob/adcb38162bb153980655868d3c26ad354d46751a/internal/provider/resource_check_http.go#L230).

**Comment by gigovich** [comment]
Hello @hatamiarash7,
Thank you for reporting the issue. We will fix it in subsequent releases.

**Comment by gigovich** [comment]
@hatamiarash7 
It fixed in the fresh version (v2.9.0)
Thank you!
